battery_max_voltage: 50
battery_min_voltage: 44
robot_max_voltage: 56.8823 #Maximal possible voltage when measurement voltage is 5V - measured with 48V
voltage_analog_port: 0
em_stop_dio_port: 0
scanner_stop_dio_port: 1

